version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DB: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: supersecretpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: messaging_app_web
    command: >
      sh -c "sleep 10 &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MYSQL_DB: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: supersecretpassword
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
