pipeline {
    agent {
        docker {
            image 'python:3.11'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
    }

    environment {
        PYTHON_VENV = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/simon21728/alx-backend-python.git'
            }
        }

        stage('Setup Python') {
            steps {
                sh 'python3 -m venv $PYTHON_VENV'
                sh './$PYTHON_VENV/bin/pip install -r requirements.txt'
                
              }
        }

        stage('Run Tests') {
            steps {
                sh 'python3 -m venv $PYTHON_VENV'
                sh './$PYTHON_VENV/bin/pip install -r requirements.txt'
                sh './$PYTHON_VENV/bin/pytest messaging_app/tests --junitxml=report.xml || true'
                
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'report.xml', allowEmptyArchive: true
        }
    }
}
